my_string = input('Введите ваше любимое хобби: ')
print(len(my_string))
print('я люблю ремонтировать технику' .upper())
print('я люблю ремонтировать технику' . lower())
print(my_string.replace(__old:= ' ', __new:= ''))
print(my_string[0])
print(my_string[-1])