my_string = input('Введите ваше любимое хобби: ')
print(len(my_string))
print('my_string' .upper())
print('my_string' . lower())
print(my_string.replace(__old:= ' ', __new:= ''))
print(my_string[0])
print(my_string[-1])
